# fly.toml app configuration file generated for drayage-quoter on 2026-02-16T20:06:20-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'drayage-quoter'
primary_region = 'ewr'

[build]

[env]
  DB_PATH = "/data/drayage.db"
  BASE_URL = "https://drayage-quoter.fly.dev"

[[mounts]]
  source = "drayage_data"
  destination = "/data"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
