 INSERT INTO ports (name, type) VALUES
     ('Atlanta', 'Rail Ramp'),
     ('Baltimore', 'Seaport'),
     ('Boston', 'Seaport'),
     ('Charlotte', 'Rail Ramp'),
     ('Charleston', 'Seaport'),
     ('Chicago', 'Rail Ramp'),
     ('Cincinnati', 'Rail Ramp'),
     ('Cleveland', 'Rail Ramp'),
     ('Columbus', 'Rail Ramp'),
     ('Dallas / Ft. Worth', 'Rail Ramp'),
     ('Detroit', 'Rail Ramp'),
     ('El Paso', 'Rail Ramp'),
     ('Everglades', 'Seaport'),
     ('Houston', 'Seaport'),
     ('Indianapolis', 'Rail Ramp'),
     ('Jacksonville', 'Seaport'),
     ('Kansas City', 'Rail Ramp'),
     ('Los Angeles / Long Beach', 'Seaport'),
     ('Louisville', 'Rail Ramp'),
     ('Memphis', 'Rail Ramp'),
     ('Miami', 'Seaport'),
     ('Minneapolis', 'Rail Ramp'),
     ('Mobile', 'Seaport'),
     ('Nashville', 'Rail Ramp'),
     ('New Orleans', 'Seaport'),
     ('New York / New Jersey', 'Seaport'),
     ('Norfolk', 'Seaport'),
     ('Oakland', 'Seaport'),
     ('Philadelphia', 'Seaport'),
     ('Pittsburgh', 'Rail Ramp'),
     ('Portland', 'Rail Ramp'),
     ('Salt Lake City', 'Rail Ramp'),
     ('Savannah', 'Seaport'),
     ('Seattle', 'Seaport'),
     ('St. Louis', 'Rail Ramp'),
     ('Tacoma', 'Seaport'),
     ('Tampa', 'Seaport'),
     ('Wimington', 'Seaport'),
     ('Test Seaport', 'Seaport'),
     ('Test Rail Ramp', 'Rail Ramp');
