CREATE TABLE markups (
  id INTEGER PRIMARY KEY,
  quote_id INTEGER NOT NULL REFERENCES quotes(id) ON DELETE CASCADE,
  lane_id INTEGER NOT NULL REFERENCES lanes(id) ON DELETE CASCADE
);
CREATE TABLE markup_items (
  id INTEGER PRIMARY KEY,
  markup_id INTEGER NOT NULL REFERENCES markups(id) ON DELETE CASCADE,
  charge_type TEXT NOT NULL,
  value REAL NOT NULL DEFAULT 0,
  markup_type TEXT NOT NULL DEFAULT 'flat'
);
